### ISSUE TITLE
Logout | Configure route | No route found for "GET https://127.0.0.1:8000/logout": Method Not Allowed (Allow: POST)

### ISSUE THREAD

**Issue by Juju075** [Juju075/snowtricks#21]

**Comment by Juju075** [comment]
security.yaml

```
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        # target: app_any_route
```
